# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='feature',
            new_name='featured',
        ),
    ]
